language:
   - cpp

install:
   - sudo apt-get update -qq
   - sudo apt-get install libgtest-dev 
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"
   - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz
   - tar -xzvf release-0.5.3.tar.gz
   - ls -l
   - cd yaml-cpp-release-0.5.3
   - cmake
   - sudo make install
   - cd "${TRAVIS_BUILD_DIR}"
   
script:
    - mkdir builds
    - cd builds
    - cmake ..
    - make
    - ctest
